pipeline {
    
    agent any

    environment {
        DOCKER_IMAGE = 'rdoneux/ptb-spa'
        // can use "pulumi stack -Q" to find this
        PULUMI_STACK = "organization/ptb-spa-iac/dev"
    }

    stages {
            stage ("Setup") {
                steps {
                    sh "npm i"
                }
                post {
                    success {
                        echo "Setup success"
                    }
                    failure {
                        echo "Setup failure"
                    }
                }
                
            }

            stage ("Build") {
                steps {
                    sh "npm run build"
                }
                post {
                    success {
                        echo "Build success"
                    }
                    failure {
                        echo "Build failure"
                    }
                }
            }

            stage ("Quality Gate: Static Analysis") {
                steps {
                    sh "npm run lint:ci"
                    sh "npm run prettier:ci"
                }
                post {
                    success {
                        echo "Static Analysis Success"
                    }
                    failure {
                        echo "Static Analysis Failure"
                    }
                }
            }

            stage ("Quality Gate: Composition Analysis") {
                steps {
                    sh "npm run test:ci"
                }
                post {
                    success {
                        echo "Quality composition analysis success"
                    }
                    failure {
                        echo "Quality composition analysis failure"
                    }
                }
            }

            stage ("Report") {
                steps {
                    clover(cloverReportDir: '../dist/coverage', cloverReportFileName: 'clover.xml',
                      healthyTarget: [methodCoverage: 70, conditionalCoverage: 80, statementCoverage: 80],
                      unhealthyTarget: [methodCoverage: 50, conditionalCoverage: 50, statementCoverage: 50],
                      failingTarget: [methodCoverage: 25, conditionalCoverage: 25, statementCoverage: 25]
                    )
                    junit 'dist/junit/junit.xml'
                }
                post {
                    success {
                        echo "Report success"
                    }
                    failure {
                        echo "Report failure"
                    }
                }
            }

            stage ("Publish to Docker Hub") {
                when {
                    branch 'master'
                }
                steps {
                    script {
                        def packageJson = readJSON(file: 'package.json')
                        env.VERSION = packageJson.version 
                        sh "docker build -t $DOCKER_IMAGE:v${env.VERSION} ."
                    }
                    withCredentials([usernamePassword(credentialsId: 'DOCKER_HUB_CREDENTIALS', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
                        sh 'echo $PASSWORD | docker login -u $USERNAME --password-stdin'
                        sh "docker push $DOCKER_IMAGE:v${env.VERSION}"
                    }
                }
                post {
                    always {
                        sh "docker rmi $DOCKER_IMAGE:v${env.VERSION} || true"                   
                    } 
                }
            }

            stage ("Deploy") {

                when {
                    anyOf {
                        branch 'master';
                    }
                }

                steps {
                    sh "curl -fsSL https://get.pulumi.com | sh"
                    sh "$HOME/.pulumi/bin/pulumi version"

                    sh "curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash"

                    withCredentials([azureServicePrincipal('AZURE_PRINCIPAL_LOGIN')]){
                        sh 'az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID'
                        sh 'az account set -s $AZURE_SUBSCRIPTION_ID'

                        withEnv(["PATH+PULUMI=$HOME/.pulumi/bin"]) {
                            withCredentials([string(credentialsId: 'AZURE_STORAGE_CONNECTION_STRING', variable: "AZURE_STORAGE_CONNECTION_STRING")]) {
                                sh "export AZURE_STORAGE_CONNECTION_STRING='${AZURE_STORAGE_CONNECTION_STRING}'"
                            }
                            sh "pulumi login"
                            dir("iac") {
                                sh "npm i"
                                sh "pulumi stack select ${PULUMI_STACK}"
                                sh "pulumi up --yes"
                            }  
                        }
                    }
                }
                post {
                    success {
                        echo "Deploy success"
                    }
                    failure {
                        echo "Deploy failure"
                    }
                }
            }
        
    }

}
